apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: output
  name: output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: output
  template:
    metadata:
      labels:
        app: output
    spec:
      containers:
        - name: output
          image: busybox
          command: ['sh']
          args: ["-c", "cat /tmp/out.txt"]
          volumeMounts:
            - mountPath: /tmp
              name: exch-vol
      restartPolicy: Always
      volumes:
        - name: exch-vol
          persistentVolumeClaim:
            claimName: exch-vol
