version: "3.9"
services:
  bc:
    # it is not working here, but --env-file compose.env does
    # env_file:
      # - compose.env
    image: busybox
    volumes:
      - exch_vol:/tmp
    environment:
      - INPUT=${INPUT}
    command: sh -c 'echo ${INPUT} | bc  > "/tmp/out.txt"'
  output:
    image: busybox
    depends_on:
      - bc
    volumes:
      - exch_vol:/tmp
    command: sh -c "cat /tmp/out.txt"

volumes:
  exch_vol:
