apiVersion: v2
name: k8_calc
description: https://github.com/banderlog/k8s_calc
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: reloader
    repository: https://stakater.github.io/stakater-charts
    version: 0.0.102
