apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: "calculateme-configmap"
  labels:
    app: bc
  name: bc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bc
  template:
    metadata:
      labels:
        app: bc
    spec:
      containers:
      - name: bc
        image: busybox
        env:
        - name: INPUT
          valueFrom:
            configMapKeyRef:
              name: calculateme-configmap
              key: calculateme
        command: ['sh']
        args: ["-c", "echo ${INPUT} | bc -l > '/tmp/index.html'"]
        volumeMounts:
        - mountPath: /tmp
          name: exch-vol
      volumes:
      - name: exch-vol
        persistentVolumeClaim:
          claimName: exch-vol
