apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    volume: exch-vol
  name: exch-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
