apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    volume: exch-vol
  name: exch-vol
spec:
#storageClassName required, see https://kubernetes.io/docs/concepts/storage/storage-classes/
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
