---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: output
  name: output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: output
  template:
    metadata:
      labels:
        app: output
    spec:
      containers:
        - name: output
          image: nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html/
              name: exch-vol
      volumes:
        - name: exch-vol
          persistentVolumeClaim:
            claimName: exch-vol