apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: output
  ports:
    # Default port used by the image (for Pod)
    - targetPort: 80
      # port on the Service
      port: 5678